import Papa from "papaparse";
import { Builder } from "xml2js";
import type { MappedRow } from "./feedMapper";
import type { ChannelFieldDef } from "./feedValidator";

export function exportCSV(rows: MappedRow[], fields: ChannelFieldDef[]): string {
  const columns = fields.map((f) => f.key);
  const data = rows.map((r) => {
    const out: Record<string, string> = {};
    for (const c of columns) out[c] = r[c] ?? "";
    return out;
  });
  return Papa.unparse({ fields: columns, data });
}

/**
 * Build an RSS 2.0-style XML feed (Google Shopping-compatible structure).
 * We deliberately keep it generic — channel-specific namespacing can be added
 * later without changing the call sites.
 */
export function exportXML(
  rows: MappedRow[],
  fields: ChannelFieldDef[],
  meta: { title: string; link?: string; description?: string }
): string {
  const items = rows.map((row) => {
    const item: Record<string, string> = {};
    for (const f of fields) {
      const v = row[f.key];
      if (v != null && v !== "") item[`g:${f.key}`] = v;
    }
    return item;
  });

  const obj = {
    rss: {
      $: { version: "2.0", "xmlns:g": "http://base.google.com/ns/1.0" },
      channel: [
        {
          title: meta.title,
          link: meta.link ?? "",
          description: meta.description ?? `${meta.title} — generated by FeedPilot`,
          item: items,
        },
      ],
    },
  };

  const builder = new Builder({
    xmldec: { version: "1.0", encoding: "UTF-8" },
    renderOpts: { pretty: true, indent: "  ", newline: "\n" },
  });
  return builder.buildObject(obj);
}
